apiVersion: apps/v1
kind: Deployment
metadata:
  name: qr-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qr-generator
  template:
    metadata:
      labels:
        app: qr-generator
    spec:
      containers:
        - name: qr-generator
          image: ghcr.io/multimoml/qr-generator:latest
          env:
            - name: ACTIVE_ENV
              value: "prod"
            - name: PORT
              value: "6002"
            - name: CONFIG_SERVER
              value: "http://multimo.dedyn.io"
            - name: CONFIG_SERVER_PORT
              value: "30000"
          ports:
            - containerPort: 6002
              name: server
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /qr/live
              port: server
            initialDelaySeconds: 30
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /qr/ready
              port: server
            initialDelaySeconds: 30
            periodSeconds: 3

---

apiVersion: v1
kind: Service
metadata:
  name: qr-generator
spec:
  type: ClusterIP
  ports:
    - port: 6002
      targetPort: server
  selector:
    app: qr-generator

---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: qr-generator
  namespace: default

spec:
  entryPoints:
    - websecure

  routes:
    - match: Host(`multimo.ml`) && PathPrefix(`/qr/`)
      kind: Rule
      services:
        - name: qr-generator
          port: 6002